/* Nage & Vélo Cardio — contenu (éducatifs, séances, plan 12 semaines, jalons) */
"use strict";

/* ---------- Éducatifs de natation ---------- */
const DRILLS = [
  { id: "crawl-complet", nage: "Nage complète", nom: "Le crawl complet (geste de référence)", niveau: "Tous niveaux",
    materiel: ["Lunettes", "Pince-nez (option)"],
    objectif: "Le modèle à avoir en tête pendant toutes vos longueurs de crawl : corps aligné, bras longs, respiration sur le côté, battements réguliers.",
    etapes: ["Corps allongé et gainé, juste sous la surface : tête dans l'axe, regard vers le fond, bassin haut.",
      "Entrée de la main devant l'épaule, doigts en premier, puis on allonge le bras vers l'avant.",
      "Traction : le coude reste haut, l'avant-bras « accroche » l'eau et la pousse vers les pieds, sous le corps.",
      "Poussée jusqu'à la cuisse, puis sortie de la main et retour aérien coude haut, bras relâché.",
      "Le corps tourne d'un côté à l'autre (roulis) à chaque bras ; on respire en tournant la tête avec ce roulis.",
      "Battements continus et souples depuis les hanches, pour équilibrer la nage."],
    erreurs: ["Tête relevée vers l'avant : les jambes coulent.",
      "Bras qui croisent l'axe du corps à l'entrée : on zigzague.",
      "Traction coude bas (on « caresse » l'eau sans la pousser).",
      "Mouvement de bras raccourci, qui s'arrête au ventre.",
      "Bloquer l'air sous l'eau."] },
  { id: "dos-complet", nage: "Nage complète", nom: "Le dos crawlé complet (geste de référence)", niveau: "Tous niveaux",
    materiel: ["Pince-nez (recommandé)", "Lunettes"],
    objectif: "Le modèle pour toutes vos longueurs de dos : tête fixe, hanches hautes, bras qui tournent en continu comme un moulin.",
    etapes: ["Allongé sur le dos, oreilles dans l'eau, regard vers le plafond, menton légèrement rentré.",
      "Hanches et ventre hauts, comme si on vous tirait par le nombril vers le plafond.",
      "Bras tendu qui sort de l'eau pouce en premier et passe à la verticale au-dessus de l'épaule.",
      "Entrée petit doigt en premier, dans l'alignement de l'épaule, puis traction coude plié jusqu'à la cuisse.",
      "Les bras sont toujours opposés : quand l'un entre dans l'eau, l'autre sort.",
      "Les épaules tournent à chaque mouvement de bras, la tête ne bouge pas. Battements continus, genoux sous l'eau."],
    erreurs: ["Être « assis » dans l'eau, bassin bas.",
      "Tête qui se relève pour regarder les pieds.",
      "Entrée de la main derrière la tête.",
      "Genoux qui sortent de l'eau (pédalage)."] },
  { id: "brasse-complet", nage: "Nage complète", nom: "La brasse complète (geste de référence)", niveau: "Tous niveaux", genou: true,
    materiel: ["Lunettes", "Pince-nez (option)", "Pas de palmes : elles ne conviennent pas aux jambes de brasse"],
    objectif: "Le modèle pour toutes vos longueurs de brasse : tirer, respirer, pousser avec les jambes, puis glisser. En brasse, ce sont surtout les jambes qui font avancer.",
    etapes: ["Départ en position « flèche » : bras tendus devant, tête entre les bras, regard vers le fond, corps allongé.",
      "Bras : les mains s'écartent un peu plus large que les épaules, puis tirent vers l'arrière et vers le bas, coudes hauts, jusqu'au niveau des épaules (jamais jusqu'aux cuisses).",
      "Respiration : pendant la traction, la tête et les épaules montent naturellement, vous inspirez par la bouche.",
      "Les mains se rejoignent sous le menton puis repartent vite vers l'avant, la tête replonge entre les bras et vous soufflez dans l'eau.",
      "Jambes : quand les bras repartent devant, ramenez les talons vers les fesses, pieds en flexion et tournés vers l'extérieur (« en canard »), puis poussez l'eau vers l'arrière avec la plante des pieds jusqu'à jambes tendues et serrées.",
      "Glisse : restez 1 à 2 secondes en flèche avant le mouvement suivant. Le rythme : tirer, respirer, pousser, glisser."],
    erreurs: ["Tirer avec les bras et pousser avec les jambes en même temps : les deux propulsions s'annulent.",
      "Garder la tête hors de l'eau tout le temps : le bassin coule et la nuque fatigue.",
      "Ramener les genoux sous le ventre au lieu des talons vers les fesses : ça freine énormément.",
      "Pieds en pointe pendant la poussée : on glisse sur l'eau sans avancer.",
      "Enchaîner les mouvements sans glisse, comme une « grenouille pressée »."] },
  { id: "bat-planche", nage: "Crawl", nom: "Battements crawl avec planche", niveau: "Débutant",
    materiel: ["Planche", "Lunettes", "Palmes (option)"],
    objectif: "Des battements efficaces qui partent des hanches, un corps gainé et horizontal. Les jambes sont de gros muscles : elles font vite monter le cardio.",
    etapes: ["Tenez la planche bras tendus, mains posées sur le bout (pas agrippées).",
      "Visage dans l'eau, regard vers le fond : soufflez vos bulles dans l'eau par la bouche et le nez.",
      "Battements courts et rapides, depuis les hanches, jambes presque tendues, chevilles relâchées et pointes de pied.",
      "Les talons affleurent la surface : l'eau doit « bouillir » derrière vous sans grandes éclaboussures.",
      "Pour inspirer, tournez la tête sur le côté (ou levez-la brièvement), puis replongez le visage."],
    erreurs: ["Plier les genoux comme si vous pédaliez : les cuisses ne travaillent plus.",
      "Garder la tête hors de l'eau tout le temps : le bassin coule et ça freine.",
      "Chevilles raides, pieds en crochet : vous n'avancez pas.",
      "Battements trop amples qui sortent largement de l'eau."] },
  { id: "rattrape", nage: "Crawl", nom: "Crawl rattrapé", niveau: "Débutant",
    materiel: ["Palmes (recommandé)", "Planche (option, tenue devant)", "Lunettes"],
    objectif: "Allonger la nage, mieux glisser et coordonner bras et respiration.",
    etapes: ["Partez bras tendus devant vous, en gardant des battements réguliers.",
      "Un bras reste devant pendant que l'autre fait un mouvement complet (traction jusqu'à la cuisse, retour aérien coude haut).",
      "La main qui revient vient toucher (« rattraper ») la main restée devant.",
      "Seulement à ce moment, l'autre bras part à son tour.",
      "Respirez du côté du bras qui tire, en tournant la tête, une lunette reste dans l'eau.",
      "Débutant : tenez une planche devant vous et touchez-la à chaque retour de bras."],
    erreurs: ["Le bras devant s'enfonce ou croise l'axe du corps.",
      "Lever la tête vers l'avant pour respirer.",
      "Oublier les battements : les jambes coulent.",
      "Traction trop courte qui s'arrête au niveau du ventre."] },
  { id: "rotation-636", nage: "Crawl", nom: "Rotation 6-3-6", niveau: "Intermédiaire",
    materiel: ["Palmes (fortement recommandé)", "Lunettes"],
    objectif: "Apprendre à tourner tout le corps autour de son axe : plus de glisse, plus de puissance et une respiration latérale facile.",
    etapes: ["Allongez-vous sur le côté droit : bras droit tendu devant, bras gauche le long du corps, épaule gauche hors de l'eau.",
      "Faites 6 battements en regardant le fond ; pour respirer, tournez juste la tête vers le plafond puis revenez.",
      "Faites 3 mouvements de bras de crawl (gauche, droit, gauche) pour basculer sur l'autre côté.",
      "Restez 6 battements sur le côté gauche, puis 3 mouvements de bras, et ainsi de suite.",
      "La rotation vient des hanches et des épaules ensemble, comme un bloc."],
    erreurs: ["Revenir à plat ventre entre les deux côtés.",
      "Lever la tête vers l'avant (le bassin coule).",
      "Bras du bas qui s'enfonce ou part vers le fond.",
      "Battements trop larges qui déséquilibrent."] },
  { id: "resp-3temps", nage: "Crawl", nom: "Respiration bilatérale 3 temps", niveau: "Débutant",
    materiel: ["Lunettes", "Pince-nez (option au début)"],
    objectif: "Un souffle régulier et une nage symétrique : vous vous essoufflez moins et tenez plus longtemps.",
    etapes: ["Soufflez en continu dans l'eau, par le nez et la bouche, dès que le visage est immergé.",
      "Inspirez tous les 3 mouvements de bras : une fois à droite, la fois suivante à gauche.",
      "Tournez la tête en même temps que le corps pivote, une lunette reste dans l'eau.",
      "Inspiration courte et rapide par la bouche, puis le visage revient aussitôt dans l'eau.",
      "Si c'est trop dur, faites 2 temps sur un 25 m puis 3 temps sur le suivant."],
    erreurs: ["Bloquer l'air sous l'eau puis tout souffler d'un coup : essoufflement rapide.",
      "Lever la tête vers l'avant ou regarder le plafond.",
      "Tirer sur la tête en arrêtant les bras.",
      "Ne respirer que du côté où l'on est à l'aise."] },
  { id: "crawl-palmes", nage: "Crawl", nom: "Crawl avec palmes (intensité)", niveau: "Débutant",
    materiel: ["Palmes", "Lunettes"],
    objectif: "Nager vite en gardant une bonne position, monter le cardio sans perdre la technique.",
    etapes: ["Mettez les palmes, partez en coulée bras tendus.",
      "Battements souples depuis les hanches, les palmes travaillent dans l'eau, pas en l'air.",
      "Gardez une traction complète et la respiration 2 ou 3 temps.",
      "Sur les répétitions rapides, augmentez la fréquence des bras sans raccourcir le mouvement."],
    erreurs: ["Ne compter que sur les palmes et ralentir les bras.",
      "Battements de genoux (pédalage) avec les palmes.",
      "Lever la tête pour regarder devant."] },
  { id: "un-bras-crawl", nage: "Crawl", nom: "Crawl un bras", niveau: "Intermédiaire",
    materiel: ["Palmes (recommandé)", "Lunettes"],
    objectif: "Travailler le trajet sous l'eau et la respiration sans se précipiter.",
    etapes: ["Un bras tendu devant (ou le long du corps quand vous êtes plus à l'aise), l'autre nage.",
      "Main qui entre dans l'eau devant l'épaule, puis traction sous le corps jusqu'à la cuisse.",
      "Respirez du côté opposé au bras qui travaille pour garder l'équilibre (ou du même côté au début).",
      "25 m bras droit, 25 m bras gauche."],
    erreurs: ["Main qui croise l'axe du corps à l'entrée.",
      "Coude qui tombe pendant la traction (on « glisse » sans pousser l'eau).",
      "Arrêt des battements."] },
  { id: "bat-dos-planche", nage: "Dos", nom: "Battements dos avec planche", niveau: "Débutant",
    materiel: ["Planche", "Pince-nez", "Palmes (option)"],
    objectif: "Une position allongée sur le dos, hanches hautes, battements efficaces.",
    etapes: ["Allongez-vous sur le dos, planche serrée contre la poitrine (ou tenue au-dessus des cuisses pour empêcher les genoux de sortir).",
      "Oreilles dans l'eau, regard vers le plafond, menton légèrement rentré.",
      "Battements depuis les hanches, jambes presque tendues : les genoux restent sous l'eau, seuls les pieds remuent la surface.",
      "Mettez le pince-nez si l'eau vous rentre dans le nez.",
      "Gardez le ventre haut, comme si on vous tirait par le nombril vers le plafond."],
    erreurs: ["Être « assis » dans l'eau : le bassin descend.",
      "Relever la tête pour regarder ses pieds.",
      "Genoux qui sortent de l'eau (pédalage).",
      "Bloquer sa respiration."] },
  { id: "dos-un-bras", nage: "Dos", nom: "Dos crawlé un bras", niveau: "Débutant",
    materiel: ["Pince-nez", "Palmes (option)"],
    objectif: "Un bon trajet de bras en dos : sortie, retour aérien et entrée dans l'eau.",
    etapes: ["Un bras le long du corps, l'autre fait le mouvement complet.",
      "Le bras sort de l'eau pouce en premier, tendu, et passe à la verticale au-dessus de l'épaule.",
      "Il entre dans l'eau petit doigt en premier, dans l'alignement de l'épaule (à « 11 h » ou « 1 h »).",
      "Sous l'eau, pliez le coude et poussez l'eau vers les pieds jusqu'à la cuisse.",
      "Tête fixe, regard au plafond. 25 m bras droit, 25 m bras gauche, puis alterné."],
    erreurs: ["Entrée de la main derrière la tête (on zigzague).",
      "Bras plié pendant le retour aérien.",
      "Tête qui bouge à chaque mouvement de bras."] },
  { id: "dos-rotation", nage: "Dos", nom: "Rotation en dos (6 battements / 3 bras)", niveau: "Intermédiaire",
    materiel: ["Palmes (recommandé)", "Pince-nez"],
    objectif: "Faire tourner les épaules en dos crawlé pour une traction plus puissante et moins de résistance.",
    etapes: ["Sur le dos, une épaule sort de l'eau, l'autre est immergée avec le bras tendu au-dessus de la tête, dans l'eau.",
      "Faites 6 battements dans cette position, tête immobile et regard au plafond.",
      "Faites 3 mouvements de bras pour basculer sur l'autre épaule.",
      "Le corps tourne comme une broche, la tête ne tourne jamais."],
    erreurs: ["Tête qui tourne avec les épaules.",
      "Bassin qui descend pendant les 6 battements.",
      "Rester à plat sans faire sortir l'épaule."] },
  { id: "br-jambes-planche", nage: "Brasse", nom: "Jambes de brasse avec planche (le fouetté)", niveau: "Débutant", genou: true,
    materiel: ["Planche", "Lunettes", "Pas de palmes"],
    objectif: "Un mouvement de jambes qui pousse vraiment l'eau vers l'arrière : c'est le moteur de la brasse. Et un bon travail de cuisses pour le cardio.",
    etapes: ["Tenez la planche bras tendus, visage dans l'eau, corps allongé et jambes serrées.",
      "1. Ramenez les talons vers les fesses en gardant les genoux à peu près écartés de la largeur des hanches (pas plus).",
      "2. Flexion des pieds : orteils vers les tibias et pointes tournées vers l'extérieur, comme un canard.",
      "3. Poussez l'eau vers l'arrière avec la plante des pieds, en dessinant un demi-cercle, jusqu'à jambes tendues.",
      "4. Pieds et jambes se rejoignent et restent serrés : glissez 1 à 2 secondes avant le mouvement suivant.",
      "Relevez le visage pour inspirer pendant le retour des talons, puis soufflez dans l'eau pendant la poussée et la glisse."],
    erreurs: ["Genoux trop écartés ou ramenés sous le ventre : ça freine et charge le genou.",
      "Pieds en pointe : vous « glissez » sur l'eau sans prise.",
      "Jambes qui ne se referment pas complètement à la fin de la poussée.",
      "Pas de glisse : on enchaîne trop vite et on s'épuise.",
      "Mouvement asymétrique (un pied en canard, l'autre en pointe) : demandez au maître-nageur de vérifier."] },
  { id: "br-jambes-dos", nage: "Brasse", nom: "Jambes de brasse sur le dos", niveau: "Débutant", genou: true,
    materiel: ["Planche (sur la poitrine ou sur le ventre)", "Pince-nez (recommandé)", "Pas de palmes"],
    objectif: "Voir et contrôler vos jambes : genoux qui restent sous l'eau, pieds bien fléchis, poussée symétrique. L'exercice idéal pour corriger son fouetté.",
    etapes: ["Allongez-vous sur le dos, planche serrée contre la poitrine, oreilles dans l'eau, hanches hautes.",
      "Pliez les jambes en descendant les talons sous vous, les genoux restent SOUS la surface.",
      "Fléchissez les pieds (orteils vers vous) et tournez-les vers l'extérieur.",
      "Poussez l'eau vers l'arrière et vers le bas en demi-cercle, jusqu'à jambes tendues et serrées.",
      "Glissez 1 à 2 secondes. Au début, relevez un peu la tête pour regarder vos pieds, puis reposez-la."],
    erreurs: ["Genoux qui sortent de l'eau : vous pliez depuis les hanches au lieu de descendre les talons.",
      "S'asseoir dans l'eau, bassin bas.",
      "Pieds en pointe : aucune propulsion.",
      "Pousser trop large, jambes qui ne se referment pas."] },
  { id: "br-bras-battements", nage: "Brasse", nom: "Bras de brasse + battements de crawl", niveau: "Débutant",
    materiel: ["Lunettes", "Palmes (option : uniquement pour les battements)", "Pince-nez (option)"],
    objectif: "Travailler le trajet des bras et la respiration de brasse sans les jambes de brasse : le corps reste à plat grâce aux battements, et le genou est épargné.",
    etapes: ["Allongé sur le ventre, battements de crawl réguliers et souples pendant tout l'exercice.",
      "Bras tendus devant, mains l'une près de l'autre, puis écartez-les un peu plus large que les épaules.",
      "Tirez vers l'arrière et vers le bas, coudes hauts, jusqu'au niveau des épaules seulement.",
      "Pendant la traction, la tête monte : inspirez par la bouche.",
      "Les mains se rejoignent sous le menton et repartent vite devant, la tête replonge, vous soufflez dans l'eau.",
      "Gardez 1 seconde bras tendus devant avant le mouvement suivant."],
    erreurs: ["Tirer jusqu'aux cuisses comme en crawl : le retour devient lent et freine.",
      "Coudes qui reculent derrière les épaules.",
      "Relever la tête très haut et la garder dehors : le bassin coule.",
      "Oublier les battements et s'arrêter entre deux bras."] },
  { id: "br-coordination", nage: "Brasse", nom: "Coordination « bras, respiration, jambes, glisse »", niveau: "Débutant", genou: true,
    materiel: ["Lunettes", "Pince-nez (option)", "Pas de palmes"],
    objectif: "Mettre les mouvements dans le bon ordre, la clé de la brasse : les bras et les jambes ne travaillent jamais en même temps.",
    etapes: ["Partez en flèche et répétez à voix haute (dans votre tête) : « tirer, respirer, pousser, glisser ».",
      "Tirer : les bras font leur traction, les jambes restent tendues et serrées.",
      "Respirer : la tête sort pendant la traction, inspiration rapide par la bouche.",
      "Pousser : les mains repartent devant et la tête replonge, puis seulement à ce moment les jambes font leur fouetté.",
      "Glisser : 2 secondes bras et jambes tendus, en soufflant dans l'eau.",
      "Au début, exagérez la glisse (comptez « 1, 2 ») ; raccourcissez-la quand le rythme est acquis."],
    erreurs: ["Bras et jambes en même temps : vous faites du surplace.",
      "Jambes qui partent avant que les bras soient revenus devant.",
      "Supprimer la glisse dès que l'on accélère.",
      "Bloquer l'air sous l'eau."] },
  { id: "br-2j1b", nage: "Brasse", nom: "2 coups de jambes pour 1 coup de bras", niveau: "Débutant +", genou: true,
    materiel: ["Lunettes", "Pas de palmes"],
    objectif: "Sentir la propulsion des jambes et garder une position bien allongée : le deuxième coup de jambes se fait en flèche, corps profilé.",
    etapes: ["Faites un mouvement de brasse complet : bras + respiration, puis jambes.",
      "Restez en flèche, bras tendus devant, tête rentrée entre les bras, et soufflez dans l'eau.",
      "Faites un deuxième coup de jambes dans cette position, sans bouger les bras.",
      "Glissez, puis reprenez un mouvement complet avec respiration.",
      "Comptez combien de cycles il vous faut pour un 25 m et essayez d'en faire moins à chaque série."],
    erreurs: ["Relever la tête pendant le deuxième coup de jambes.",
      "Bras qui s'écartent ou s'enfoncent pendant les jambes seules.",
      "Aller trop vite : gardez un petit temps d'arrêt après chaque poussée."] },
  { id: "br-glisse", nage: "Brasse", nom: "Glisse longue : compter ses mouvements", niveau: "Débutant +", genou: true,
    materiel: ["Lunettes", "Pas de palmes"],
    objectif: "Nager plus loin avec moins d'effort : une brasse efficace, c'est moins de mouvements par longueur. Très utile pour récupérer activement entre deux séries de crawl.",
    etapes: ["Nagez la brasse complète en comptant chaque mouvement (1 cycle bras + jambes = 1).",
      "Après chaque poussée de jambes, tenez la flèche 2 secondes, tête rentrée, en soufflant dans l'eau.",
      "Notez votre nombre de mouvements pour 25 m (souvent 12 à 16 au début).",
      "Sur les longueurs suivantes, essayez d'en enlever 1 ou 2 en allongeant la glisse et en poussant mieux avec les jambes.",
      "Ne pas confondre glisse et arrêt : reprenez le mouvement avant de ralentir complètement."],
    erreurs: ["Glisser tête relevée : le corps freine comme une ancre.",
      "Glisser trop longtemps jusqu'à s'arrêter, puis repartir de zéro.",
      "Raccourcir la poussée des jambes pour aller plus vite."] },
  { id: "br-virage", nage: "Brasse", nom: "Virage brasse (toucher à 2 mains)", niveau: "Débutant",
    materiel: ["Lunettes", "Pince-nez (option)"],
    objectif: "Enchaîner les longueurs de brasse sans s'arrêter au mur : le toucher à deux mains est obligatoire en brasse.",
    etapes: ["Arrivez au mur bras tendus et touchez-le avec les DEUX mains en même temps, à la même hauteur.",
      "Ramenez les genoux vers la poitrine, une main lâche le mur et passe sous l'eau vers l'autre bout du bassin.",
      "L'autre main quitte le mur en passant au-dessus de la tête ; inspirez pendant la rotation.",
      "Pieds au mur, immergez-vous et poussez sur le côté, bras tendus devant, mains l'une sur l'autre.",
      "Glissez en flèche, puis un mouvement de bras, un coup de jambes, et reprenez la nage."],
    erreurs: ["Toucher d'une seule main ou une main après l'autre.",
      "S'accrocher au mur et souffler : on perd le rythme cardio.",
      "Pousser vers la surface au lieu de pousser droit.",
      "Reprendre la nage trop tôt, sans glisse."] },
  { id: "virage-simple", nage: "Général", nom: "Virage simple et coulée", niveau: "Débutant",
    materiel: ["Lunettes", "Pince-nez (option)"],
    objectif: "Enchaîner les longueurs sans pause pour nager en continu : indispensable pour l'endurance.",
    etapes: ["En arrivant au mur, touchez-le d'une main (crawl) ou en regardant derrière vous (dos).",
      "Ramenez les genoux vers la poitrine et tournez-vous, pieds contre le mur.",
      "Inspirez, immergez-vous et poussez fort sur le mur, sur le côté, bras tendus devant, mains l'une sur l'autre.",
      "Glissez en position « flèche » 2 à 3 secondes, quelques battements, puis reprenez la nage.",
      "Soufflez par le nez pendant la coulée (ou mettez le pince-nez)."],
    erreurs: ["S'arrêter et souffler au mur : c'est là qu'on perd le rythme cardio.",
      "Pousser vers la surface au lieu de pousser droit.",
      "Reprendre les bras trop tôt, sans glisser."] },
  { id: "bat-intensifs", nage: "Général", nom: "Battements intensifs avec planche", niveau: "Débutant",
    materiel: ["Planche", "Palmes (option pour aller plus vite)"],
    objectif: "Du fractionné jambes pour faire grimper le cardio, très utile pour un footballeur.",
    etapes: ["Même position que les battements planche, mais à fond sur la durée demandée.",
      "Accélérez la fréquence plutôt que l'amplitude.",
      "Gardez le visage dans l'eau le plus possible pour garder le corps à plat.",
      "Respectez le repos : il fait partie de l'exercice."],
    erreurs: ["Partir trop vite sur la première répétition et exploser ensuite.",
      "Genoux qui plient, battements qui sortent de l'eau.",
      "Tirer sur la planche avec les bras."] },
  { id: "hypoxie", nage: "Crawl", nom: "Respiration 5 temps (hypoxie légère progressive)", niveau: "Intermédiaire",
    securite: true,
    materiel: ["Lunettes", "Maître-nageur présent"],
    objectif: "Mieux gérer le manque d'air et le CO₂, comme en fin de match. Il s'agit d'espacer un peu les respirations, jamais de faire de l'apnée.",
    etapes: ["Uniquement en piscine surveillée, jamais seul, et prévenez le maître-nageur ou un partenaire.",
      "Ne faites JAMAIS d'hyperventilation (respirations rapides et profondes) avant : c'est la cause des syncopes.",
      "Nagez en crawl tranquille (effort 5/10) en respirant tous les 5 mouvements de bras, en soufflant doucement et en continu.",
      "Au moindre inconfort, reprenez une respiration tous les 3 temps ou 2 temps, immédiatement.",
      "Repos complet de 30 s minimum entre chaque 25 m. Jamais de longueur en apnée sous l'eau."],
    erreurs: ["Forcer malgré l'envie de respirer : arrêtez-vous dès que c'est désagréable.",
      "Enchaîner sans repos ou chercher à « battre un record ».",
      "Le faire en fin de séance quand vous êtes très fatigué.",
      "Le faire seul ou sans surveillance."] }
];

/* ---------- Séances ----------
   step : n = répétitions, d = distance (m) par répétition, s = durée (s) par répétition,
          r = repos après chaque répétition (s), rpe = effort 1-10, drill = id d'éducatif, test = clé de test */
const PH = { E: "Échauffement", T: "Éducatifs", C: "Corps cardio", R: "Retour au calme" };

const SESSIONS = [
  /* ---- NATATION ---- */
  { id: "N1", type: "natation", titre: "Bases du crawl et du souffle", niveau: "Débutant", focus: "Respiration, battements, endurance de base",
    steps: [
      { p: "E", n: 4, d: 50, r: 15, rpe: 3, nom: "Nage souple au choix", how: "Crawl, dos et brasse alternés, sans forcer. Soufflez bien dans l'eau." },
      { p: "T", n: 4, d: 25, r: 20, rpe: 5, nom: "Battements crawl planche", drill: "bat-planche" },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "Crawl rattrapé avec palmes", drill: "rattrape" },
      { p: "C", n: 8, d: 25, r: 20, rpe: 6, nom: "Crawl respiration 3 temps", drill: "resp-3temps", how: "Même vitesse sur chaque 25 m. Si 3 temps est trop dur, respirez en 2 temps." },
      { p: "C", n: 4, d: 50, r: 30, rpe: 5, nom: "25 dos + 25 crawl", how: "Allure régulière, le dos sert à récupérer en restant actif." },
      { p: "R", n: 1, d: 100, r: 0, rpe: 2, nom: "Dos souple", how: "Très facile, respiration ample." } ] },
  { id: "N2", type: "natation", titre: "Endurance douce et dos crawlé", niveau: "Débutant", focus: "Endurance aérobie, dos crawlé",
    steps: [
      { p: "E", n: 4, d: 50, r: 15, rpe: 3, nom: "Nage souple crawl / dos", how: "Alternez crawl et dos à chaque 50 m." },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "Battements dos planche", drill: "bat-dos-planche" },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "Dos un bras", drill: "dos-un-bras", how: "1 bras droit, 1 bras gauche, puis alterné." },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "Jambes de brasse sur le dos", drill: "br-jambes-dos", how: "Découverte de la brasse : genoux sous l'eau, pieds en canard, sans forcer sur le genou." },
      { p: "C", n: 3, d: 100, r: 40, rpe: 6, nom: "100 m crawl régulier", how: "Une allure que vous pouvez tenir, souffle contrôlé. Si besoin : 50 crawl / 50 dos." },
      { p: "C", n: 6, d: 25, r: 20, rpe: 7, nom: "Battements intensifs planche", drill: "bat-intensifs" },
      { p: "R", n: 1, d: 100, r: 0, rpe: 2, nom: "Brasse ou dos souple", how: "Relâchez tout, grande glisse." } ] },
  { id: "N3", type: "natation", titre: "Pyramide découverte", niveau: "Débutant", focus: "Gestion de l'allure, montée du cardio",
    steps: [
      { p: "E", n: 2, d: 100, r: 20, rpe: 3, nom: "100 crawl souple puis 100 dos", how: "Le 1er en crawl, le 2e en dos." },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "Rotation 6-3-6 avec palmes", drill: "rotation-636" },
      { p: "T", n: 4, d: 25, r: 15, rpe: 5, nom: "Respiration 3 temps", drill: "resp-3temps" },
      { p: "C", n: 1, d: 25, r: 20, rpe: 6, nom: "Pyramide : 25 m crawl" },
      { p: "C", n: 1, d: 50, r: 25, rpe: 6, nom: "Pyramide : 50 m crawl" },
      { p: "C", n: 1, d: 75, r: 30, rpe: 7, nom: "Pyramide : 75 m crawl" },
      { p: "C", n: 1, d: 100, r: 40, rpe: 7, nom: "Pyramide : 100 m crawl", how: "Le sommet : régularité, pas de sprint." },
      { p: "C", n: 1, d: 75, r: 30, rpe: 7, nom: "Pyramide : 75 m crawl" },
      { p: "C", n: 1, d: 50, r: 25, rpe: 7, nom: "Pyramide : 50 m crawl" },
      { p: "C", n: 1, d: 25, r: 30, rpe: 8, nom: "Pyramide : 25 m crawl", how: "Le dernier un peu plus vite." },
      { p: "C", n: 4, d: 25, r: 30, rpe: 8, nom: "Crawl palmes vite", drill: "crawl-palmes" },
      { p: "R", n: 1, d: 100, r: 0, rpe: 2, nom: "Brasse souple (ou dos)", drill: "br-glisse", how: "Retour au calme : grande glisse, respiration ample, sans palmes." } ] },
  { id: "N4", type: "natation", titre: "Fractionné 8×25 et 6×50", niveau: "Débutant +", focus: "Fractionné, VO2",
    steps: [
      { p: "E", n: 4, d: 50, r: 15, rpe: 3, nom: "Nage souple crawl / dos" },
      { p: "T", n: 4, d: 25, r: 15, rpe: 4, nom: "Crawl rattrapé", drill: "rattrape" },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "Rotation en dos avec palmes", drill: "dos-rotation" },
      { p: "C", n: 8, d: 25, r: 30, rpe: 8, nom: "25 m crawl rapide", how: "Vite mais technique propre. Repartez au bip." },
      { p: "C", n: 1, d: 100, r: 30, rpe: 2, nom: "Récupération active en brasse", drill: "br-glisse", how: "Brasse très lente avec grande glisse (ou dos). Le cœur redescend sans s'arrêter." },
      { p: "C", n: 6, d: 50, r: 30, rpe: 7, nom: "50 m crawl soutenu", how: "Allure soutenue et identique sur les 6." },
      { p: "R", n: 1, d: 100, r: 0, rpe: 2, nom: "Nage souple au choix" } ] },
  { id: "N5", type: "natation", titre: "Continu et battements", niveau: "Intermédiaire", focus: "Endurance continue, nage sans arrêt",
    steps: [
      { p: "E", n: 1, d: 200, r: 30, rpe: 3, nom: "200 m souple", how: "Crawl et dos au choix, sans s'arrêter." },
      { p: "T", n: 4, d: 25, r: 15, rpe: 5, nom: "Respiration 3 temps", drill: "resp-3temps" },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "Virage simple et coulée", drill: "virage-simple", how: "Faites un virage au bout de chaque longueur." },
      { p: "C", n: 1, d: 300, r: 60, rpe: 6, nom: "300 m crawl continu", how: "Sans s'arrêter, avec virages. Si besoin, 10 s de pause au mur, pas plus." },
      { p: "C", n: 6, d: 25, r: 20, rpe: 7, nom: "Battements soutenus planche", drill: "bat-intensifs", how: "Soutenu mais pas à fond : séance du vendredi, on garde des jambes fraîches pour le match." },
      { p: "C", n: 4, d: 50, r: 20, rpe: 5, nom: "50 m dos régulier" },
      { p: "C", n: 4, d: 25, r: 20, rpe: 5, nom: "25 m brasse « tirer, respirer, pousser, glisser »", drill: "br-coordination", how: "Allure tranquille, l'ordre des mouvements avant la vitesse." },
      { p: "R", n: 1, d: 100, r: 0, rpe: 2, nom: "Nage souple au choix" } ] },
  { id: "N6", type: "natation", titre: "Fractionné VO2 avec palmes", niveau: "Intermédiaire", focus: "Haute intensité, VO2max",
    steps: [
      { p: "E", n: 4, d: 50, r: 15, rpe: 3, nom: "Nage souple crawl / dos" },
      { p: "E", n: 4, d: 25, r: 15, rpe: 5, nom: "Battements crawl planche", drill: "bat-planche" },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "Rotation 6-3-6 avec palmes", drill: "rotation-636" },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "Dos un bras", drill: "dos-un-bras" },
      { p: "C", n: 6, d: 25, r: 20, rpe: 9, nom: "Crawl palmes très vite (série 1)", drill: "crawl-palmes" },
      { p: "C", n: 1, d: 100, r: 30, rpe: 2, nom: "Récupération active en brasse", drill: "br-glisse", how: "Brasse très lente avec grande glisse (ou dos très lent)." },
      { p: "C", n: 6, d: 25, r: 20, rpe: 9, nom: "Crawl palmes très vite (série 2)", drill: "crawl-palmes" },
      { p: "C", n: 4, d: 50, r: 30, rpe: 7, nom: "50 m crawl sans palmes, soutenu" },
      { p: "R", n: 1, d: 100, r: 0, rpe: 2, nom: "Dos souple" } ] },
  { id: "N7", type: "natation", titre: "Seuil : 100 m répétés", niveau: "Intermédiaire", focus: "Seuil, régularité",
    steps: [
      { p: "E", n: 3, d: 100, r: 20, rpe: 3, nom: "100 crawl, 100 dos, 100 crawl rattrapé (palmes)" },
      { p: "T", n: 4, d: 25, r: 15, rpe: 5, nom: "Respiration 3 temps", drill: "resp-3temps" },
      { p: "T", n: 4, d: 25, r: 15, rpe: 5, nom: "Battements dos planche", drill: "bat-dos-planche" },
      { p: "C", n: 5, d: 100, r: 30, rpe: 7, nom: "100 m crawl au seuil", how: "Allure « difficile mais tenable ». Le dernier aussi rapide que le premier." },
      { p: "C", n: 4, d: 25, r: 20, rpe: 7, nom: "25 m brasse tonique", drill: "brasse-complet", how: "Rythme soutenu mais glisse conservée. Genou sensible : remplacez par du crawl." },
      { p: "C", n: 4, d: 25, r: 40, rpe: 9, nom: "25 m sprint crawl" },
      { p: "R", n: 1, d: 100, r: 0, rpe: 2, nom: "Nage souple au choix" } ] },
  { id: "N8", type: "natation", titre: "Pyramide intensive + souffle", niveau: "Intermédiaire", focus: "Seuil, gestion du souffle",
    steps: [
      { p: "E", n: 3, d: 100, r: 20, rpe: 3, nom: "100 crawl, 100 dos, 100 crawl" },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "Rotation 6-3-6 avec palmes", drill: "rotation-636" },
      { p: "T", n: 4, d: 25, r: 30, rpe: 5, nom: "Respiration 5 temps (hypoxie légère)", drill: "hypoxie", how: "⚠️ Uniquement sous surveillance. Arrêtez au moindre inconfort. Jamais d'hyperventilation." },
      { p: "C", n: 1, d: 50, r: 20, rpe: 7, nom: "Pyramide : 50 m crawl" },
      { p: "C", n: 1, d: 100, r: 30, rpe: 7, nom: "Pyramide : 100 m crawl" },
      { p: "C", n: 1, d: 150, r: 40, rpe: 7, nom: "Pyramide : 150 m crawl", how: "Le sommet : allure régulière." },
      { p: "C", n: 1, d: 100, r: 30, rpe: 8, nom: "Pyramide : 100 m crawl" },
      { p: "C", n: 1, d: 50, r: 30, rpe: 8, nom: "Pyramide : 50 m crawl", how: "Finissez plus vite." },
      { p: "C", n: 8, d: 25, r: 20, rpe: 8, nom: "Battements intensifs planche", drill: "bat-intensifs" },
      { p: "R", n: 1, d: 100, r: 0, rpe: 2, nom: "Brasse ou dos souple", how: "Grande glisse, respiration ample." } ] },
  { id: "N9", type: "natation", titre: "Endurance longue", niveau: "Intermédiaire", focus: "Endurance aérobie, volume",
    steps: [
      { p: "E", n: 4, d: 50, r: 15, rpe: 3, nom: "Nage souple crawl / dos" },
      { p: "T", n: 4, d: 25, r: 15, rpe: 4, nom: "Crawl rattrapé", drill: "rattrape" },
      { p: "T", n: 4, d: 25, r: 15, rpe: 4, nom: "Rotation en dos", drill: "dos-rotation" },
      { p: "C", n: 1, d: 400, r: 60, rpe: 6, nom: "400 m crawl continu", how: "Respiration 3 temps quand c'est possible, virages sans pause." },
      { p: "C", n: 4, d: 50, r: 20, rpe: 6, nom: "50 m : 25 brasse + 25 dos", how: "Brasse avec glisse, dos régulier : on varie les nages sans casser l'allure." },
      { p: "C", n: 4, d: 50, r: 30, rpe: 7, nom: "50 m crawl descendant", how: "Chaque 50 m un peu plus vite que le précédent." },
      { p: "R", n: 1, d: 100, r: 0, rpe: 2, nom: "Nage souple au choix" } ] },
  { id: "N10", type: "natation", titre: "Affûtage et vitesse", niveau: "Intermédiaire", focus: "Qualité, vitesse, fraîcheur",
    steps: [
      { p: "E", n: 4, d: 50, r: 15, rpe: 3, nom: "Nage souple crawl / dos" },
      { p: "T", n: 4, d: 25, r: 15, rpe: 5, nom: "Respiration 3 temps", drill: "resp-3temps" },
      { p: "T", n: 4, d: 25, r: 15, rpe: 4, nom: "Dos un bras", drill: "dos-un-bras" },
      { p: "C", n: 6, d: 50, r: 30, rpe: 7, nom: "50 m crawl allure tenue" },
      { p: "C", n: 6, d: 25, r: 40, rpe: 9, nom: "Crawl palmes sprint", drill: "crawl-palmes" },
      { p: "C", n: 2, d: 100, r: 30, rpe: 6, nom: "100 m 3 nages : 25 brasse + 25 dos + 50 crawl", how: "Enchaînez les nages sans pause, allure régulière." },
      { p: "R", n: 1, d: 100, r: 0, rpe: 2, nom: "Dos souple" } ] },
  { id: "N11", type: "natation", titre: "Technique & aisance : crawl, dos, brasse", niveau: "Débutant +", focus: "Technique 3 nages, aérobie modéré, jambes épargnées",
    steps: [
      { p: "E", n: 4, d: 50, r: 15, rpe: 3, nom: "Nage souple crawl / dos / brasse", how: "Changez de nage à chaque 50 m." },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "Crawl un bras", drill: "un-bras-crawl", how: "25 m bras droit, 25 m bras gauche." },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "Dos un bras", drill: "dos-un-bras" },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "2 coups de jambes pour 1 coup de bras (brasse)", drill: "br-2j1b", how: "Comptez vos cycles par 25 m." },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "Virage brasse (toucher 2 mains)", drill: "br-virage", how: "Un virage propre au bout de chaque longueur." },
      { p: "C", n: 3, d: 100, r: 30, rpe: 6, nom: "100 m crawl aérobie", how: "Nage longue et relâchée, respiration 3 temps si possible. Même allure sur les 3." },
      { p: "C", n: 4, d: 50, r: 20, rpe: 5, nom: "50 m : 25 dos + 25 brasse", how: "Tête fixe en dos, glisse en brasse." },
      { p: "R", n: 1, d: 100, r: 0, rpe: 2, nom: "Nage souple au choix" } ] },
  { id: "N12", type: "natation", titre: "Endurance technique : 200 m répétés", niveau: "Intermédiaire", focus: "Aérobie, nage continue, technique sous fatigue",
    steps: [
      { p: "E", n: 1, d: 200, r: 30, rpe: 3, nom: "200 m souple", how: "Crawl et dos au choix, sans s'arrêter." },
      { p: "T", n: 4, d: 25, r: 15, rpe: 4, nom: "Rotation 6-3-6 avec palmes", drill: "rotation-636" },
      { p: "T", n: 4, d: 25, r: 15, rpe: 4, nom: "Crawl rattrapé", drill: "rattrape" },
      { p: "C", n: 3, d: 200, r: 45, rpe: 6, nom: "200 m crawl continu", how: "Allure confortable, virages sans pause, respiration 3 temps le plus souvent possible." },
      { p: "C", n: 4, d: 50, r: 20, rpe: 5, nom: "50 m dos avec rotation des épaules", drill: "dos-rotation" },
      { p: "C", n: 4, d: 25, r: 15, rpe: 4, nom: "25 m brasse glisse longue", drill: "br-glisse", how: "Récupération active : comptez vos mouvements, essayez d'en faire moins à chaque 25 m." },
      { p: "R", n: 1, d: 100, r: 0, rpe: 2, nom: "Nage souple au choix" } ] },
  { id: "N13", type: "natation", titre: "Découverte de la brasse + aérobie", niveau: "Débutant", focus: "Technique brasse, aérobie modéré",
    steps: [
      { p: "E", n: 4, d: 50, r: 15, rpe: 3, nom: "Nage souple crawl / dos", how: "Alternez crawl et dos à chaque 50 m." },
      { p: "T", n: 4, d: 25, r: 20, rpe: 3, nom: "Jambes de brasse sur le dos", drill: "br-jambes-dos", how: "Regardez vos genoux : ils restent sous l'eau." },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "Jambes de brasse avec planche", drill: "br-jambes-planche", how: "Talons vers les fesses, pieds en canard, glisse. Sans palmes." },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "Bras de brasse + battements de crawl", drill: "br-bras-battements", how: "Palmes possibles ici, uniquement pour les battements." },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "Coordination « tirer, respirer, pousser, glisser »", drill: "br-coordination" },
      { p: "C", n: 4, d: 50, r: 20, rpe: 5, nom: "50 m brasse complète régulière", drill: "brasse-complet", how: "Allure tranquille : glisse à chaque mouvement." },
      { p: "C", n: 4, d: 50, r: 20, rpe: 6, nom: "50 m crawl aérobie", how: "Respiration 3 temps si possible, même allure sur les 4." },
      { p: "R", n: 1, d: 100, r: 0, rpe: 2, nom: "Dos souple" } ] },
  { id: "N14", type: "natation", titre: "Brasse glisse + 3 nages", niveau: "Débutant +", focus: "Glisse en brasse, nage continue en 3 nages",
    steps: [
      { p: "E", n: 1, d: 200, r: 30, rpe: 3, nom: "200 m souple : 50 crawl, 50 dos, 50 brasse, 50 crawl" },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "2 coups de jambes pour 1 coup de bras", drill: "br-2j1b" },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "Glisse longue : comptez vos mouvements", drill: "br-glisse", how: "Notez votre nombre de mouvements au 1er 25 m, puis enlevez-en 1 ou 2." },
      { p: "T", n: 4, d: 25, r: 20, rpe: 4, nom: "Virage brasse (toucher 2 mains)", drill: "br-virage" },
      { p: "C", n: 4, d: 100, r: 30, rpe: 6, nom: "100 m 3 nages : 25 brasse + 25 dos + 50 crawl", how: "Sans pause entre les nages, allure régulière et souffle contrôlé." },
      { p: "C", n: 4, d: 25, r: 30, rpe: 6, nom: "25 m brasse un peu plus vite", drill: "brasse-complet", how: "Plus de rythme, mais glisse conservée et pas de sprint : on est à 48 h du match." },
      { p: "C", n: 2, d: 100, r: 30, rpe: 6, nom: "100 m crawl aérobie", how: "Nage longue et relâchée." },
      { p: "R", n: 1, d: 100, r: 0, rpe: 2, nom: "Brasse souple, grande glisse", drill: "br-glisse" } ] },
  { id: "TN", type: "natation", test: true, titre: "Test cardio natation", niveau: "Tous niveaux", focus: "Mesurer vos progrès : 12 min + 100 m",
    steps: [
      { p: "E", n: 1, d: 200, r: 20, rpe: 3, nom: "200 m souple" },
      { p: "E", n: 4, d: 25, r: 20, rpe: 6, nom: "25 m progressif", how: "Chaque 25 m un peu plus vite." },
      { p: "C", n: 1, s: 720, r: 180, rpe: 9, nom: "TEST : distance max en 12 min", test: "swim12", how: "Comptez vos longueurs. Allure régulière, crawl de préférence (dos ou brasse autorisés pour récupérer), sans s'arrêter si possible. Notez le total à la fin." },
      { p: "C", n: 1, d: 100, r: 180, rpe: 2, nom: "Récupération active", how: "Très souple, puis 3 min de repos." },
      { p: "C", n: 1, d: 100, r: 0, rpe: 10, nom: "TEST : 100 m crawl chronométré", test: "swim100", how: "Départ dans l'eau, poussée au mur. Arrêtez le chrono en touchant le mur." },
      { p: "R", n: 1, d: 200, r: 0, rpe: 2, nom: "Nage souple au choix" } ] },

  /* ---- VÉLO ---- */
  { id: "V1", type: "velo", titre: "Endurance zone 2", niveau: "Tous niveaux", focus: "Base aérobie, récupération",
    steps: [
      { p: "E", n: 1, s: 600, r: 0, rpe: 3, nom: "Échauffement progressif", how: "Commencez très facile, montez doucement. Cadence 85-95 tr/min." },
      { p: "C", n: 1, s: 1800, r: 0, rpe: 4, nom: "Zone 2 continue", how: "Test de la parole : vous pouvez parler en phrases complètes. Restez régulier, même en côte (petit braquet)." },
      { p: "R", n: 1, s: 300, r: 0, rpe: 2, nom: "Retour au calme", how: "Très facile, jambes qui tournent." } ] },
  { id: "V2", type: "velo", titre: "Récupération active", niveau: "Tous niveaux", focus: "Récupération après match ou semaine chargée",
    steps: [
      { p: "E", n: 1, s: 300, r: 0, rpe: 2, nom: "Mise en route très facile" },
      { p: "C", n: 1, s: 1200, r: 0, rpe: 3, nom: "Zone 1 en vélocité", how: "Petit braquet, cadence 90-100 tr/min, aucune sensation d'effort. Vous pourriez chanter." },
      { p: "R", n: 1, s: 300, r: 0, rpe: 2, nom: "Retour au calme" } ] },
  { id: "V3", type: "velo", titre: "Fractionné 30/30", niveau: "Débutant +", focus: "VO2max, répétition des efforts (comme en match)",
    steps: [
      { p: "E", n: 1, s: 720, r: 0, rpe: 3, nom: "Échauffement progressif", how: "10 min faciles, les 2 dernières un peu plus soutenues." },
      { p: "C", n: 8, s: 30, r: 30, rpe: 8, nom: "30 s fort / 30 s très facile (série 1)", how: "Effort 8/10, vous ne pouvez plus parler. Pendant les 30 s faciles, continuez à pédaler." },
      { p: "C", n: 1, s: 240, r: 0, rpe: 2, nom: "Récupération entre les séries", how: "Pédalez tranquille, buvez." },
      { p: "C", n: 8, s: 30, r: 30, rpe: 8, nom: "30 s fort / 30 s très facile (série 2)" },
      { p: "R", n: 1, s: 480, r: 0, rpe: 2, nom: "Retour au calme" } ] },
  { id: "V4", type: "velo", titre: "Fractionné 1 min / 1 min", niveau: "Débutant +", focus: "VO2max",
    steps: [
      { p: "E", n: 1, s: 720, r: 0, rpe: 3, nom: "Échauffement progressif" },
      { p: "C", n: 10, s: 60, r: 60, rpe: 8, nom: "1 min fort / 1 min facile", how: "Effort 8/10 : phrases impossibles, quelques mots seulement. Gardez la même intensité sur les 10." },
      { p: "R", n: 1, s: 480, r: 0, rpe: 2, nom: "Retour au calme" } ] },
  { id: "V5", type: "velo", titre: "Tempo", niveau: "Intermédiaire", focus: "Endurance soutenue, seuil aérobie",
    steps: [
      { p: "E", n: 1, s: 600, r: 0, rpe: 3, nom: "Échauffement progressif" },
      { p: "C", n: 3, s: 420, r: 180, rpe: 6, nom: "7 min tempo (zone 3)", how: "Effort 6/10 : vous parlez en phrases courtes. Régulier du début à la fin." },
      { p: "R", n: 1, s: 300, r: 0, rpe: 2, nom: "Retour au calme" } ] },
  { id: "V6", type: "velo", titre: "4 × 4 min (VO2max)", niveau: "Intermédiaire", focus: "Le classique pour booster la VO2max",
    steps: [
      { p: "E", n: 1, s: 600, r: 0, rpe: 3, nom: "Échauffement progressif" },
      { p: "E", n: 2, s: 30, r: 60, rpe: 7, nom: "Accélération 30 s", how: "Pour préparer le cœur à l'effort." },
      { p: "C", n: 4, s: 240, r: 180, rpe: 9, nom: "4 min dur (zone 4-5)", how: "Effort 8-9/10, 85-95 % de la FC max. Dur mais tenable 4 min. Récup 3 min en pédalant facile." },
      { p: "R", n: 1, s: 300, r: 0, rpe: 2, nom: "Retour au calme" } ] },
  { id: "V7", type: "velo", titre: "Côtes", niveau: "Intermédiaire", focus: "Puissance, cardio, force des jambes",
    steps: [
      { p: "E", n: 1, s: 720, r: 0, rpe: 3, nom: "Échauffement vers votre côte", how: "Choisissez une côte de 1 à 2 min. Sans côte : gros braquet sur le plat." },
      { p: "C", n: 6, s: 90, r: 150, rpe: 8, nom: "1 min 30 de montée", how: "Assis, cadence 70-80, effort 8/10. Les 2 dernières : 20 s en danseuse à la fin. Redescendez tranquille." },
      { p: "R", n: 1, s: 540, r: 0, rpe: 2, nom: "Retour au calme" } ] },
  { id: "V8", type: "velo", titre: "Endurance longue zone 2", niveau: "Intermédiaire", focus: "Volume aérobie, foncier",
    steps: [
      { p: "E", n: 1, s: 600, r: 0, rpe: 3, nom: "Échauffement progressif" },
      { p: "C", n: 1, s: 2700, r: 0, rpe: 4, nom: "Zone 2 continue (45 min)", how: "Test de la parole : phrases complètes. Buvez toutes les 15 min." },
      { p: "R", n: 1, s: 300, r: 0, rpe: 2, nom: "Retour au calme" } ] },
  { id: "V9", type: "velo", titre: "Pyramide 1-2-3-2-1", niveau: "Intermédiaire", focus: "VO2max, gestion de l'effort",
    steps: [
      { p: "E", n: 1, s: 720, r: 0, rpe: 3, nom: "Échauffement progressif" },
      { p: "C", n: 1, s: 60, r: 60, rpe: 8, nom: "1 min fort" },
      { p: "C", n: 1, s: 120, r: 120, rpe: 8, nom: "2 min fort" },
      { p: "C", n: 1, s: 180, r: 180, rpe: 8, nom: "3 min fort", how: "Le sommet : régulier, ne partez pas trop vite." },
      { p: "C", n: 1, s: 120, r: 120, rpe: 8, nom: "2 min fort" },
      { p: "C", n: 1, s: 60, r: 60, rpe: 9, nom: "1 min fort", how: "Videz le réservoir." },
      { p: "R", n: 1, s: 480, r: 0, rpe: 2, nom: "Retour au calme" } ] },
  { id: "V10", type: "velo", titre: "Seuil 2 × 10 min", niveau: "Intermédiaire", focus: "Seuil, tenir un effort long",
    steps: [
      { p: "E", n: 1, s: 720, r: 0, rpe: 3, nom: "Échauffement progressif" },
      { p: "C", n: 2, s: 600, r: 300, rpe: 7, nom: "10 min au seuil (zone 4 basse)", how: "Effort 7/10 : quelques mots seulement, mais vous tenez. Respiration forte et rythmée." },
      { p: "R", n: 1, s: 300, r: 0, rpe: 2, nom: "Retour au calme" } ] },
  { id: "V11", type: "velo", titre: "Endurance & vélocité", niveau: "Tous niveaux", focus: "Récupération active + technique de pédalage (lendemain de match)",
    steps: [
      { p: "E", n: 1, s: 600, r: 0, rpe: 3, nom: "Échauffement progressif", how: "Très facile au début, cadence 85-95 tr/min." },
      { p: "C", n: 1, s: 900, r: 0, rpe: 4, nom: "Zone 2 continue", how: "Test de la parole : phrases complètes. Petit braquet." },
      { p: "C", n: 4, s: 60, r: 120, rpe: 4, nom: "1 min de vélocité (100-110 tr/min)", how: "Petit braquet, on tourne vite les jambes SANS forcer : bassin immobile sur la selle. 2 min tranquilles entre chaque." },
      { p: "R", n: 1, s: 300, r: 0, rpe: 2, nom: "Retour au calme" } ] },
  { id: "V12", type: "velo", titre: "Activation veille de match", niveau: "Tous niveaux", focus: "Optionnel : réveiller les jambes sans se fatiguer",
    steps: [
      { p: "E", n: 1, s: 600, r: 0, rpe: 2, nom: "Pédalage très facile", how: "Zone 1, aucune sensation d'effort." },
      { p: "C", n: 3, s: 15, r: 105, rpe: 5, nom: "Accélération souple de 15 s", how: "Cadence haute (100-110 tr/min), en souplesse, pas en force. Juste réveiller les jambes." },
      { p: "R", n: 1, s: 300, r: 0, rpe: 2, nom: "Retour au calme", how: "Puis étirements doux, hydratation et bonne nuit de sommeil." } ] },
  { id: "TV", type: "velo", test: true, titre: "Test vélo 20 min", niveau: "Tous niveaux", focus: "Mesurer vos progrès : distance en 20 min",
    steps: [
      { p: "E", n: 1, s: 600, r: 0, rpe: 3, nom: "Échauffement progressif", how: "Allez jusqu'au début de votre parcours test (toujours le même, plat, peu de feux)." },
      { p: "E", n: 3, s: 30, r: 60, rpe: 7, nom: "Accélération 30 s" },
      { p: "C", n: 1, s: 1200, r: 0, rpe: 9, test: "bike20", nom: "TEST : 20 min effort max régulier", how: "Le plus loin possible en 20 min, effort régulier (ne partez pas trop vite). Notez la distance (compteur ou appli) et votre FC moyenne si vous avez une montre." },
      { p: "R", n: 1, s: 600, r: 0, rpe: 2, nom: "Retour au calme" } ] }
];

/* ---------- Plan 12 semaines, construit autour du foot ----------
   Foot : entraînement mardi + jeudi, match dimanche.
   Créneaux : [lundi : vélo récup (J+1), mercredi : séance clé, vendredi : natation technique + aérobie, samedi : activation optionnelle]
   alt = séance de fractionné vélo à faire UNIQUEMENT si un entraînement de foot est annulé. */
const PLAN = [
  { w: 1, phase: "Fondations", note: "Semaine de départ : test vélo le mercredi, test natation le vendredi. Votre cours de natation du jeudi est un bonus, pas une obligation.", s: ["V2", "TV", "TN", "V12"], test: true, alt: null },
  { w: 2, phase: "Fondations", note: "On installe la technique et le souffle, sans se mettre dans le rouge. Premiers mouvements de brasse le vendredi.", s: ["V2", "N1", "N2", "V12"], alt: "V3" },
  { w: 3, phase: "Fondations", note: "Première vraie séance de fractionné en natation le mercredi, découverte de la brasse le vendredi.", s: ["V1", "N3", "N13", "V12"], alt: "V4" },
  { w: 4, phase: "Fondations", note: "Semaine allégée + tests : comparez avec la semaine 1.", s: ["V2", "TV", "TN", "V12"], test: true, alt: null },
  { w: 5, phase: "Développement", note: "Le fractionné natation monte d'un cran, le vendredi reste en aisance.", s: ["V1", "N4", "N5", "V12"], alt: "V5" },
  { w: 6, phase: "Développement", note: "Séance VO2 avec palmes le mercredi : la plus dure du bloc. Vendredi : glisse en brasse et 3 nages.", s: ["V11", "N6", "N14", "V12"], alt: "V6" },
  { w: 7, phase: "Développement", note: "Seuil le mercredi, endurance longue le vendredi.", s: ["V1", "N7", "N9", "V12"], alt: "V7" },
  { w: 8, phase: "Développement", note: "Semaine allégée + tests de mi-parcours.", s: ["V2", "TV", "TN", "V12"], test: true, alt: null },
  { w: 9, phase: "Performance", note: "Pyramide intensive le mercredi, 200 m répétés le vendredi.", s: ["V11", "N8", "N12", "V12"], alt: "V6" },
  { w: 10, phase: "Performance", note: "Retour du VO2 avec palmes : vous devez sentir le progrès. Vendredi : technique crawl, dos et brasse.", s: ["V1", "N6", "N11", "V12"], alt: "V9" },
  { w: 11, phase: "Performance", note: "Affûtage : qualité et vitesse, sans fatigue inutile.", s: ["V11", "N10", "N12", "V12"], alt: "V10" },
  { w: 12, phase: "Performance", note: "Semaine allégée + tests finaux : le moment de mesurer vos progrès.", s: ["V2", "TV", "TN", "V12"], test: true, alt: null }
];
const SLOT_DAYS = [0, 2, 4, 5]; // lundi, mercredi, vendredi, samedi (0 = lundi)
const SLOT_LABEL = ["Lundi · récup J+1", "Mercredi · séance clé", "Vendredi · technique + aérobie", "Samedi · option veille de match"];
const OPTIONAL_SLOTS = [3];
const REQUIRED_SLOTS = [0, 1, 2];
const WEEK_TEMPLATE = [
  { j: "Lundi", t: "Vélo récupération / endurance douce", ic: "🚴", info: "Lendemain de match : 25 à 45 min en zone 1-2 pour faire tourner les jambes et éliminer la fatigue. Si le match a été très dur ou si vous avez des courbatures, faites la récupération active (20 min)." },
  { j: "Mardi", t: "Entraînement de foot", ic: "⚽", info: "Pas de séance de l'application. L'entraînement compte comme une séance intense." },
  { j: "Mercredi", t: "Séance clé : natation cardio", ic: "🏊", info: "À 72 h du match et loin du suivant : c'est le meilleur jour pour l'intensité. Nager fait travailler le cœur sans chocs pour les jambes, l'entraînement du jeudi n'est donc pas pénalisé. Semaines de tests : test vélo ce jour-là." },
  { j: "Jeudi", t: "Entraînement de foot", ic: "⚽", info: "Cours de natation (ex. ce jeudi à 13 h 30) : un bonus facultatif, à faire en mode technique, sans forcer. Notez-le en « séance libre / cours » si vous y allez." },
  { j: "Vendredi", t: "Natation technique + aérobie modéré", ic: "🏊", info: "À 48 h du match : effort modéré (RPE 7 maximum), pas de sprint ni de grosse série de jambes. C'est le jour des éducatifs de brasse, en volume modéré pour ménager les genoux. Semaines de tests : test natation ce jour-là." },
  { j: "Samedi", t: "Repos (ou activation très légère, facultative)", ic: "😴", info: "Veille de match : rien d'intense. Repos complet, ou 20 min de vélo très facile avec 3 accélérations souples. Hydratation et sommeil." },
  { j: "Dimanche", t: "Match de foot", ic: "⚽", info: "Le match compte comme une grosse séance de cardio." }
];
const FOOT_LOGIC = [
  "Votre semaine compte déjà 3 efforts intenses de foot (entraînements mardi et jeudi, match dimanche). L'application ajoute 3 séances, plus une option, sans jamais doubler une journée de foot.",
  "Lundi, lendemain de match : vélo très facile. Le pédalage sans impact fait circuler le sang et accélère la récupération.",
  "Mercredi : séance clé de la semaine. C'est le jour le plus loin des deux matchs (J+3 et J−4), et la natation fait monter le cardio sans chocs ni contacts : les jambes restent disponibles pour le jeudi.",
  "Vendredi, à 48 h du match : natation technique et aérobie modérée. On progresse en souffle et en geste sans arriver fatigué le dimanche.",
  "Samedi, veille de match : repos, ou 20 min d'activation très légère si vous en avez envie. Jamais d'intensité.",
  "Le fractionné vélo (30/30, 4 × 4 min, côtes, seuil) reste dans la bibliothèque. Faites-le seulement si un entraînement de foot du mardi ou du jeudi est annulé : c'est la séance « remplacement » indiquée chaque semaine.",
  "Les cours de natation sont un bonus : faites-les en technique, sans ajouter d'intensité les jours d'entraînement.",
  "La brasse arrive surtout le vendredi (technique) et comme récupération active dans les séances du mercredi. Le mouvement de jambes de brasse sollicite l'intérieur du genou : volume modéré, jamais de grosse série de jambes de brasse avant un match.",
  "Semaines 4, 8 et 12 : semaines allégées avec les tests. Si vous êtes très fatigué ou si vous avez deux matchs dans la semaine, sautez la séance du vendredi."
];

/* ---------- Jalons techniques ---------- */
const MILESTONES = [
  { id: "m1", g: "Crawl", t: "Battements depuis les hanches, genoux presque tendus" },
  { id: "m2", g: "Crawl", t: "Respirer sur le côté sans lever la tête (une lunette dans l'eau)" },
  { id: "m3", g: "Crawl", t: "Respiration 3 temps sur 50 m" },
  { id: "m4", g: "Crawl", t: "Crawl rattrapé propre sur 25 m sans palmes" },
  { id: "m5", g: "Crawl", t: "100 m crawl sans s'arrêter" },
  { id: "m6", g: "Crawl", t: "200 m crawl sans s'arrêter" },
  { id: "m7", g: "Crawl", t: "400 m crawl continu" },
  { id: "m8", g: "Dos", t: "25 m dos crawlé sans que la tête bouge" },
  { id: "m9", g: "Dos", t: "Sortie pouce en premier, entrée petit doigt en premier" },
  { id: "m10", g: "Dos", t: "Rotation des épaules en dos" },
  { id: "m11", g: "Dos", t: "100 m dos crawlé sans s'arrêter" },
  { id: "m17", g: "Brasse", t: "Jambes de brasse : talons vers les fesses, pieds en canard, genoux sous l'eau" },
  { id: "m18", g: "Brasse", t: "Bras et jambes jamais en même temps (« tirer, respirer, pousser, glisser »)" },
  { id: "m19", g: "Brasse", t: "25 m brasse avec glisse (2 s en flèche à chaque mouvement)" },
  { id: "m20", g: "Brasse", t: "25 m brasse en 12 mouvements ou moins" },
  { id: "m21", g: "Brasse", t: "50 m brasse sans s'arrêter" },
  { id: "m22", g: "Brasse", t: "Virage brasse : toucher 2 mains + coulée sans pause" },
  { id: "m12", g: "Général", t: "Virage simple + coulée sans pause au mur" },
  { id: "m13", g: "Souffle", t: "Nager 10 min sans pause" },
  { id: "m14", g: "Souffle", t: "Nager 20 min sans pause" },
  { id: "m15", g: "Vélo", t: "Tenir 45 min en zone 2 sans dépasser" },
  { id: "m16", g: "Vélo", t: "Terminer un 4 × 4 min complet" }
];

/* ---------- Tests ---------- */
const TESTS = {
  swim12: { nom: "Natation 12 min", unite: "m", mieux: "haut", fmt: v => Math.round(v) + " m" },
  swim100: { nom: "100 m crawl", unite: "s", mieux: "bas", fmt: v => fmtMMSS(v) },
  bike20: { nom: "Vélo 20 min", unite: "km", mieux: "haut", fmt: v => (Math.round(v * 10) / 10).toString().replace(".", ",") + " km" },
  fcRepos: { nom: "FC de repos (au réveil)", unite: "bpm", mieux: "bas", fmt: v => Math.round(v) + " bpm" }
};
function fmtMMSS(s) { s = Math.round(s); return Math.floor(s / 60) + ":" + String(s % 60).padStart(2, "0"); }

/* ---------- Niveaux ---------- */
const LEVELS = ["Débutant motivé", "Nageur du dimanche", "Cardio en rodage", "Souffle solide", "Moteur diesel",
  "Machine aérobie", "Poumons d'acier", "Triathlète en herbe", "Endurance de fer", "Légende du cardio"];

/* ---------- Guide ---------- */
const ZONES = [
  { z: 1, nom: "Récupération", pct: [50, 60], rpe: "1-2", parole: "Vous pourriez chanter." },
  { z: 2, nom: "Endurance", pct: [60, 70], rpe: "3-4", parole: "Phrases complètes, respiration aisée." },
  { z: 3, nom: "Tempo", pct: [70, 80], rpe: "5-6", parole: "Phrases courtes." },
  { z: 4, nom: "Seuil", pct: [80, 90], rpe: "7-8", parole: "Quelques mots seulement." },
  { z: 5, nom: "VO2max", pct: [90, 100], rpe: "9-10", parole: "Impossible de parler." }
];
const SAFETY = {
  natation: ["Nagez toujours en piscine surveillée.", "Hypoxie (respiration espacée) : jamais seul, jamais d'hyperventilation avant, jamais d'apnée sous l'eau, arrêt au moindre inconfort.",
    "Brasse et genou : le fouetté sollicite l'intérieur du genou. Si votre genou gauche (ou l'autre) est douloureux ou encore bandé, ne forcez pas le mouvement de jambes : faites un fouetté plus petit, ou remplacez les jambes de brasse par des battements de crawl. Douleur pendant ou après : stop et avis médical.",
    "Pas de palmes pour les jambes de brasse : elles forcent sur les genoux et les chevilles.",
    "Buvez avant et après : on transpire aussi dans l'eau.", "Douleur dans la poitrine, vertige, palpitations : arrêtez immédiatement et prévenez le maître-nageur.",
    "Votre FC est 10 à 15 battements plus basse en natation qu'à vélo pour un même effort : fiez-vous surtout à l'effort ressenti (RPE)."],
  velo: ["Casque toujours attaché.", "Visibilité : éclairage avant et arrière, gilet ou vêtements clairs, surtout l'hiver.",
    "Fractionné : choisissez une route calme ou une piste cyclable, jamais de sprint en ville ou aux intersections.",
    "Hydratation : un bidon pour toute sortie de plus de 30 min ; mangez quelque chose au-delà d'1 h.",
    "Avant de partir : pneus gonflés, freins qui répondent, chaîne graissée.", "Gardez les yeux sur la route, pas sur le téléphone : lancez le minuteur avant de partir, il bipe tout seul."],
  general: ["Pas d'intensité la veille d'un match, et jamais de fractionné vélo la veille d'un entraînement de foot.",
    "Match décalé au samedi ? Décalez tout d'un jour : vélo récup le dimanche, rien d'intense le vendredi.",
    "Douleur articulaire ou fatigue anormale : remplacez la séance par de la récupération active.",
    "En cas de doute sur votre santé (antécédents cardiaques, essoufflement inhabituel), demandez l'avis d'un médecin."]
};
